
require("./SlideShow.module.css");
const styles = {
  bmaster: 'bmaster_bddd2e7e',
  teams: 'teams_bddd2e7e',
  ContainerBmaster: 'ContainerBmaster_bddd2e7e',
  upperMenu: 'upperMenu_bddd2e7e',
  logo: 'logo_bddd2e7e',
  slogen: 'slogen_bddd2e7e',
  search: 'search_bddd2e7e',
  inner: 'inner_bddd2e7e',
  micro: 'micro_bddd2e7e',
  magni: 'magni_bddd2e7e',
  input: 'input_bddd2e7e',
  mobileMenu: 'mobileMenu_bddd2e7e',
  mobileSearch: 'mobileSearch_bddd2e7e',
  topSeperator: 'topSeperator_bddd2e7e',
  right: 'right_bddd2e7e',
  center: 'center_bddd2e7e',
  left: 'left_bddd2e7e',
  right_courses: 'right_courses_bddd2e7e',
  center_courses: 'center_courses_bddd2e7e',
  left_courses: 'left_courses_bddd2e7e',
  right_oneCourse: 'right_oneCourse_bddd2e7e',
  center_oneCourse: 'center_oneCourse_bddd2e7e',
  left_oneCourse: 'left_oneCourse_bddd2e7e',
  slideShow: 'slideShow_bddd2e7e',
  rightArrow: 'rightArrow_bddd2e7e',
  images: 'images_bddd2e7e',
  gallery: 'gallery_bddd2e7e',
  oneImage: 'oneImage_bddd2e7e',
  text: 'text_bddd2e7e',
  line1: 'line1_bddd2e7e',
  line2: 'line2_bddd2e7e',
  line3: 'line3_bddd2e7e',
  leftArrow: 'leftArrow_bddd2e7e',
  galleryButtons: 'galleryButtons_bddd2e7e',
  inside: 'inside_bddd2e7e',
  oneButton: 'oneButton_bddd2e7e',
  bottomSeperator: 'bottomSeperator_bddd2e7e',
  sections: 'sections_bddd2e7e',
  oneItem: 'oneItem_bddd2e7e',
  title: 'title_bddd2e7e',
  coursesSection: 'coursesSection_bddd2e7e',
  oneCourse: 'oneCourse_bddd2e7e',
  courseName: 'courseName_bddd2e7e',
  smallButton: 'smallButton_bddd2e7e',
  buttons: 'buttons_bddd2e7e'
};

export default styles;
