
require("./TopNav.module.css");
const styles = {
  bmaster: 'bmaster_acb7baab',
  teams: 'teams_acb7baab',
  ContainerBmaster: 'ContainerBmaster_acb7baab',
  imgSlogen: 'imgSlogen_acb7baab',
  searchIcon: 'searchIcon_acb7baab',
  upperMenu: 'upperMenu_acb7baab',
  search: 'search_acb7baab',
  inner: 'inner_acb7baab',
  managerButton: 'managerButton_acb7baab',
  mobileSearchToggle: 'mobileSearchToggle_acb7baab',
  logo: 'logo_acb7baab',
  slogen: 'slogen_acb7baab',
  micro: 'micro_acb7baab',
  magni: 'magni_acb7baab',
  input: 'input_acb7baab',
  mobileMenu: 'mobileMenu_acb7baab',
  mobileSearch: 'mobileSearch_acb7baab',
  topSeperator: 'topSeperator_acb7baab',
  right: 'right_acb7baab',
  center: 'center_acb7baab',
  left: 'left_acb7baab',
  right_courses: 'right_courses_acb7baab',
  center_courses: 'center_courses_acb7baab',
  left_courses: 'left_courses_acb7baab',
  right_oneCourse: 'right_oneCourse_acb7baab',
  center_oneCourse: 'center_oneCourse_acb7baab',
  left_oneCourse: 'left_oneCourse_acb7baab',
  managerText: 'managerText_acb7baab',
  managerIcon: 'managerIcon_acb7baab',
  slideShow: 'slideShow_acb7baab',
  coursesSection: 'coursesSection_acb7baab',
  oneCourse: 'oneCourse_acb7baab',
  sections: 'sections_acb7baab',
  oneItem: 'oneItem_acb7baab',
  text: 'text_acb7baab',
  smallButton: 'smallButton_acb7baab',
  hideOnMobile: 'hideOnMobile_acb7baab',
  rightArrow: 'rightArrow_acb7baab',
  images: 'images_acb7baab',
  gallery: 'gallery_acb7baab',
  oneImage: 'oneImage_acb7baab',
  leftArrow: 'leftArrow_acb7baab',
  hideOnMobileSearch: 'hideOnMobileSearch_acb7baab',
  courseName: 'courseName_acb7baab',
  buttons: 'buttons_acb7baab',
  mobileVisible: 'mobileVisible_acb7baab'
};

export default styles;
